admin:
    resource: "@AdminBundle/Resources/config/routing.yml"
    prefix:   /

clients:
    resource: "@ClientsBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: "@AppBundle/Controller/"
    type:     annotation
